import React from "react";
import styles from "../style";
import GetStarted from "./GetStarted";
import "../circle.css";

const Hero = () => {
  return (
    // use id=home as we want to add scroll and we can control DOM elements through id

    <section
      id="home"
      className={`flex md:flex-row flex-col ${styles.paddingY}`}
    >
      <div
        className={`flex-1 ${styles.flexStart} flex-col xl:px-0 sm:px-16 px-6`}
      >
        {/* <div className="flex flex-row items-center py-[6px] px-4 bg-discount-gradient rounded-[10px] mb-2"> */}
        {/* <img src={discount} alt="discount" className="w-[32px] h-[32px]" /> */}
        {/* <p className={`${styles.paragraph} ml-2`}>
            <span className="text-white">20%</span> Discount For{" "}
            <span className="text-white"> 1 Month</span> Account
          </p> */}
        {/* </div> */}

        <div
          className="flex flex-row
        justify-between items-center w-full"
        >
          {/* Use flex-1 to allow a flex item to grow and shrink as needed, ignoring its initial size  */}

          <h2
            className="flex-1 font-poppins
          font-semibold ss:text-[52px] text-[52px] text-white ss:leading-[52px] leading-[55px]"
          >
            Empowering DeFi Safety with{" "}
            <br
              className="sm:block
            hidden"
            />{" "}
            <span className="text-gradient">GNN-Powered</span>{" "}
          </h2>
          <div className="ss:flex hidden md:mr-4 mr-0">
            <GetStarted />
          </div>
        </div>
        <h2
          className="font-poppins
        font-semibold ss:text-[52px] text-[52px]
        text-white ss:leading-[42px] leading-[75px] w-full"
        >
          Transaction Integrity.
        </h2>
        <p className={`${styles.paragraph} max-w-[470px] mt-5`}>
          7236 transactions analyzed, 91.4% more accurate than flashbots We
          don't need your ABIs unlike existing solutions.
        </p>
        {/* 7236 transactions analyzed, 91.4% more accurate than flashbots
        We don't need your ABIs unlike existing solutions. */}
      </div>

      <div
        className={`flex-1 flex ${styles.flexCenter} md:my-0 my-10 relative`}
      >
        {/* z-[5] because we wan tout robot image to appear on top of gradient */}
        {/* <img src={robot} alt="billing" className='w-[100%] relative z-[5]'/>} */}
        <div className="relative z-[5] w-[100%] mt-10 py-2 ">
          <ol reversed className="paces" lang="en">
            <li className="pace js text-l">
              SOLUTION
              <blockquote className="quote js">
                AntiMEV: Enhancing DeFi security by preventing Maximum
                Extractable Value (MEV) exploits with advanced GNN-powered
                transaction integrity solutions.
              </blockquote>
            </li>
            <li className="pace css text-l">
              PROBLEM
              <blockquote className="quote css">
                The negative effects of MEV and arbitrage on the consensus layer
                include increased network congestion, higher transaction fees,
                and potential centralization risks, which can undermine the
                security and fairness of the blockchain.
              </blockquote>
            </li>
            <li className="pace html text-l">
              NO MEV !
              <blockquote className="quote html">
                Maximum Extractable Value is problematic because it allows
                arbitrage bots and miners to exploit transaction ordering,
                leading to increased transaction costs, market manipulation, and
                an overall less fair and efficient blockchain ecosystem.
              </blockquote>
            </li>
            <li className="pace url text-l">
              ARBITRAGE
              <blockquote className="quote url">
                Arbitrage: Exploiting price differences in different markets to
                make a profit.
              </blockquote>
            </li>
            <li className="pace http text-l">
              MEV
              <blockquote className="quote http">
                MEV: Maximum Extractable Value, profits generated by miners
                through transaction ordering.
              </blockquote>
            </li>
            <li className="pace tcpip text-l">
              GNN
              <blockquote className="quote tcpip">
                Graph Neural Networks are a class of neural networks tailored
                for analyzing graph-structured data, enabling them to capture
                intricate relationships among interconnected entities.
              </blockquote>
            </li>
          </ol>
        </div>

        {/* gradient start */}
        <div className="absolute z-[0] w-[40%] h-[35%] top-0 pink__gradient" />
        <div className="absolute z-[1] w-[80%] h-[80%] rounded-full white__gradient bottom-40" />
        <div className="absolute z-[0] w-[50%] h-[50%] right-20 bottom-20 blue__gradient" />
        {/* gradient end */}
      </div>

      <div className={`ss:hidden ${styles.flexCenter}`}>
        {/* <GetStarted /> */}
      </div>
    </section>
  );
};

export default Hero;
